import { WineEntry } from './types';

export const mockWineData: WineEntry[] = [
  {
    id: "1",
    name: 'Château Margaux',
    vintage: 2015,
    varietal: 'Bordeaux Blend',
    country: 'France',
    rating: 10,
    description: 'Exceptional complexity and depth. Aromas of blackcurrant, violet, and cedar. A truly memorable wine.',
    notes: 'Opened for our 10th anniversary. Lives up to the hype. Incredibly smooth with a finish that lasts forever.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-10-26T10:00:00Z',
    publicRating: 4.9,
    reviewCount: 1850,
    ratingSource: 'Vivino',
    price: 950,
  },
  {
    id: "2",
    name: 'Opus One',
    vintage: 2018,
    varietal: 'Cabernet Sauvignon',
    country: 'USA',
    rating: 10,
    description: 'Bold and powerful. Notes of dark chocolate, blackberry, and a hint of vanilla. Will age beautifully.',
    notes: 'A gift from a client. Paired perfectly with a ribeye steak. So rich and decadent.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-09-15T14:30:00Z',
    publicRating: 4.8,
    reviewCount: 3200,
    ratingSource: 'Vivino',
    price: 375,
  },
  {
    id: "3",
    name: 'Cloudy Bay',
    vintage: 2022,
    varietal: 'Sauvignon Blanc',
    country: 'New Zealand',
    rating: 8,
    description: 'Classic Marlborough Sauvignon Blanc. Crisp and vibrant with passionfruit and citrus notes. Perfect for a summer day.',
    notes: 'Our go-to for a sunny afternoon on the patio. Super refreshing.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-10-10T18:45:00Z',
    publicRating: 4.6,
    reviewCount: 55000,
    ratingSource: 'Vivino',
    price: 30,
  },
  {
    id: "4",
    name: 'Penfolds Grange',
    vintage: 2017,
    varietal: 'Shiraz',
    country: 'Australia',
    rating: 10,
    description: 'An iconic Australian Shiraz. Rich and full-bodied with layers of dark fruit, spice, and mocha.',
    notes: 'Waited years to open this one. Worth it. Intense flavor but surprisingly balanced.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-08-01T12:00:00Z',
    publicRating: 4.8,
    reviewCount: 1100,
    ratingSource: 'Wine.com',
    price: 700,
  },
  {
    id: "5",
    name: 'Domaine de la Romanée-Conti',
    vintage: 2016,
    varietal: 'Pinot Noir',
    country: 'France',
    rating: 10,
    description: 'The pinnacle of Burgundy. Ethereal and elegant with incredible purity of fruit and silky tannins.',
    notes: 'Tasted a small glass at a wine event. A once-in-a-lifetime experience. Absolutely sublime.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-05-20T20:15:00Z',
    publicRating: 4.9,
    reviewCount: 540,
    ratingSource: 'Vivino',
    price: 25000,
  },
  {
    id: "6",
    name: 'Catena Zapata Malbec',
    vintage: 2019,
    varietal: 'Malbec',
    country: 'Argentina',
    rating: 8,
    description: 'A benchmark for Argentinian Malbec. Ripe red and black fruits, with a smooth, lingering finish.',
    notes: 'Great value. Never disappoints for a casual dinner. Pairs well with almost anything.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-10-22T11:00:00Z',
    publicRating: 4.5,
    reviewCount: 12500,
    ratingSource: 'Vivino',
    price: 25,
  },
  {
    id: "7",
    name: 'Veuve Clicquot Yellow Label',
    vintage: 0, // Non-Vintage
    varietal: 'Champagne Blend',
    country: 'France',
    rating: 8,
    description: 'Reliably delicious. Fine bubbles, notes of apple, pear, and brioche. Great for celebrations.',
    notes: 'Popped a bottle for New Year\'s Eve. Classic and always a crowd-pleaser.',
    imageUrl: 'https://i.postimg.cc/xdvXnqyP/Wine-bottle.jpg',
    dateAdded: '2023-07-11T19:00:00Z',
    publicRating: 4.7,
    reviewCount: 98000,
    ratingSource: 'Vivino',
    price: 60,
  },
];